title: Test Just the Docs Template
description: Test A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://kpitz.github.io/test_just_the_docs_website

aux_links:
  Template Repository: https://github.com/kpitz/test_just_the_docs_website
